// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiggyScaleApi.Models;

#nullable disable

namespace PiggyScaleApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240830150014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PiggyScaleApi.Models.User", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userpassword");

                    b.HasKey("userId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("PiggyScaleApi.Models.Weight", b =>
                {
                    b.Property<long>("weightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("weightid");

                    b.Property<uint>("boxNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("box");

                    b.Property<string>("dateTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("datetime");

                    b.Property<float>("stddev")
                        .HasColumnType("REAL")
                        .HasColumnName("stddev");

                    b.Property<uint>("userid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<float>("weight")
                        .HasColumnType("REAL")
                        .HasColumnName("weight");

                    b.HasKey("weightId");

                    b.HasIndex("weightId")
                        .IsUnique();

                    b.ToTable("weight");
                });
#pragma warning restore 612, 618
        }
    }
}
